/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminConceptualRouteImport } from './routes/admin-conceptual'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as CertificadoRouteImport } from './routes/certificado'
import { Route as CompartirRouteImport } from './routes/compartir'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PerfilNuevoRouteImport } from './routes/perfil-nuevo'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as TemporadasRouteImport } from './routes/temporadas'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as MisionMisionIdIndexRouteImport } from './routes/mision.$misionId.index'
import { Route as MisionMisionIdJugarRouteImport } from './routes/mision.$misionId.jugar'
import { Route as MisionMisionIdResultadosRouteImport } from './routes/mision.$misionId.resultados'
import { Route as MisionMisionIdRetoRouteImport } from './routes/mision.$misionId.reto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConceptualRoute = AdminConceptualRouteImport.update({
  id: '/admin-conceptual',
  path: '/admin-conceptual',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoRoute = CertificadoRouteImport.update({
  id: '/certificado',
  path: '/certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const CompartirRoute = CompartirRouteImport.update({
  id: '/compartir',
  path: '/compartir',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilNuevoRoute = PerfilNuevoRouteImport.update({
  id: '/perfil-nuevo',
  path: '/perfil-nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const TemporadasRoute = TemporadasRouteImport.update({
  id: '/temporadas',
  path: '/temporadas',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const MisionMisionIdIndexRoute = MisionMisionIdIndexRouteImport.update({
  id: '/mision/$misionId/',
  path: '/mision/$misionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MisionMisionIdJugarRoute = MisionMisionIdJugarRouteImport.update({
  id: '/mision/$misionId/jugar',
  path: '/mision/$misionId/jugar',
  getParentRoute: () => rootRouteImport,
} as any)
const MisionMisionIdResultadosRoute =
  MisionMisionIdResultadosRouteImport.update({
    id: '/mision/$misionId/resultados',
    path: '/mision/$misionId/resultados',
    getParentRoute: () => rootRouteImport,
  } as any)
const MisionMisionIdRetoRoute = MisionMisionIdRetoRouteImport.update({
  id: '/mision/$misionId/reto',
  path: '/mision/$misionId/reto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-conceptual': typeof AdminConceptualRoute
  '/avatar': typeof AvatarRoute
  '/bienvenida': typeof BienvenidaRoute
  '/certificado': typeof CertificadoRoute
  '/compartir': typeof CompartirRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/perfil-nuevo': typeof PerfilNuevoRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/temporadas': typeof TemporadasRoute
  '/tutorial': typeof TutorialRoute
  '/mision/$misionId/jugar': typeof MisionMisionIdJugarRoute
  '/mision/$misionId/resultados': typeof MisionMisionIdResultadosRoute
  '/mision/$misionId/reto': typeof MisionMisionIdRetoRoute
  '/mision/$misionId/': typeof MisionMisionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-conceptual': typeof AdminConceptualRoute
  '/avatar': typeof AvatarRoute
  '/bienvenida': typeof BienvenidaRoute
  '/certificado': typeof CertificadoRoute
  '/compartir': typeof CompartirRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/perfil-nuevo': typeof PerfilNuevoRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/temporadas': typeof TemporadasRoute
  '/tutorial': typeof TutorialRoute
  '/mision/$misionId/jugar': typeof MisionMisionIdJugarRoute
  '/mision/$misionId/resultados': typeof MisionMisionIdResultadosRoute
  '/mision/$misionId/reto': typeof MisionMisionIdRetoRoute
  '/mision/$misionId': typeof MisionMisionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-conceptual': typeof AdminConceptualRoute
  '/avatar': typeof AvatarRoute
  '/bienvenida': typeof BienvenidaRoute
  '/certificado': typeof CertificadoRoute
  '/compartir': typeof CompartirRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/perfil-nuevo': typeof PerfilNuevoRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/temporadas': typeof TemporadasRoute
  '/tutorial': typeof TutorialRoute
  '/mision/$misionId/jugar': typeof MisionMisionIdJugarRoute
  '/mision/$misionId/resultados': typeof MisionMisionIdResultadosRoute
  '/mision/$misionId/reto': typeof MisionMisionIdRetoRoute
  '/mision/$misionId/': typeof MisionMisionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-conceptual'
    | '/avatar'
    | '/bienvenida'
    | '/certificado'
    | '/compartir'
    | '/login'
    | '/perfil'
    | '/perfil-nuevo'
    | '/ranking'
    | '/registro'
    | '/temporadas'
    | '/tutorial'
    | '/mision/$misionId/jugar'
    | '/mision/$misionId/resultados'
    | '/mision/$misionId/reto'
    | '/mision/$misionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-conceptual'
    | '/avatar'
    | '/bienvenida'
    | '/certificado'
    | '/compartir'
    | '/login'
    | '/perfil'
    | '/perfil-nuevo'
    | '/ranking'
    | '/registro'
    | '/temporadas'
    | '/tutorial'
    | '/mision/$misionId/jugar'
    | '/mision/$misionId/resultados'
    | '/mision/$misionId/reto'
    | '/mision/$misionId'
  id:
    | '__root__'
    | '/'
    | '/admin-conceptual'
    | '/avatar'
    | '/bienvenida'
    | '/certificado'
    | '/compartir'
    | '/login'
    | '/perfil'
    | '/perfil-nuevo'
    | '/ranking'
    | '/registro'
    | '/temporadas'
    | '/tutorial'
    | '/mision/$misionId/jugar'
    | '/mision/$misionId/resultados'
    | '/mision/$misionId/reto'
    | '/mision/$misionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminConceptualRoute: typeof AdminConceptualRoute
  AvatarRoute: typeof AvatarRoute
  BienvenidaRoute: typeof BienvenidaRoute
  CertificadoRoute: typeof CertificadoRoute
  CompartirRoute: typeof CompartirRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PerfilNuevoRoute: typeof PerfilNuevoRoute
  RankingRoute: typeof RankingRoute
  RegistroRoute: typeof RegistroRoute
  TemporadasRoute: typeof TemporadasRoute
  TutorialRoute: typeof TutorialRoute
  MisionMisionIdJugarRoute: typeof MisionMisionIdJugarRoute
  MisionMisionIdResultadosRoute: typeof MisionMisionIdResultadosRoute
  MisionMisionIdRetoRoute: typeof MisionMisionIdRetoRoute
  MisionMisionIdIndexRoute: typeof MisionMisionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-conceptual': {
      id: '/admin-conceptual'
      path: '/admin-conceptual'
      fullPath: '/admin-conceptual'
      preLoaderRoute: typeof AdminConceptualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado': {
      id: '/certificado'
      path: '/certificado'
      fullPath: '/certificado'
      preLoaderRoute: typeof CertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compartir': {
      id: '/compartir'
      path: '/compartir'
      fullPath: '/compartir'
      preLoaderRoute: typeof CompartirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-nuevo': {
      id: '/perfil-nuevo'
      path: '/perfil-nuevo'
      fullPath: '/perfil-nuevo'
      preLoaderRoute: typeof PerfilNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temporadas': {
      id: '/temporadas'
      path: '/temporadas'
      fullPath: '/temporadas'
      preLoaderRoute: typeof TemporadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mision/$misionId/': {
      id: '/mision/$misionId/'
      path: '/mision/$misionId'
      fullPath: '/mision/$misionId/'
      preLoaderRoute: typeof MisionMisionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mision/$misionId/jugar': {
      id: '/mision/$misionId/jugar'
      path: '/mision/$misionId/jugar'
      fullPath: '/mision/$misionId/jugar'
      preLoaderRoute: typeof MisionMisionIdJugarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mision/$misionId/resultados': {
      id: '/mision/$misionId/resultados'
      path: '/mision/$misionId/resultados'
      fullPath: '/mision/$misionId/resultados'
      preLoaderRoute: typeof MisionMisionIdResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mision/$misionId/reto': {
      id: '/mision/$misionId/reto'
      path: '/mision/$misionId/reto'
      fullPath: '/mision/$misionId/reto'
      preLoaderRoute: typeof MisionMisionIdRetoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminConceptualRoute: AdminConceptualRoute,
  AvatarRoute: AvatarRoute,
  BienvenidaRoute: BienvenidaRoute,
  CertificadoRoute: CertificadoRoute,
  CompartirRoute: CompartirRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PerfilNuevoRoute: PerfilNuevoRoute,
  RankingRoute: RankingRoute,
  RegistroRoute: RegistroRoute,
  TemporadasRoute: TemporadasRoute,
  TutorialRoute: TutorialRoute,
  MisionMisionIdJugarRoute: MisionMisionIdJugarRoute,
  MisionMisionIdResultadosRoute: MisionMisionIdResultadosRoute,
  MisionMisionIdRetoRoute: MisionMisionIdRetoRoute,
  MisionMisionIdIndexRoute: MisionMisionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
